name: Build

on:
  release:
    types: [published]
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.10]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        working-directory: ./ossso_app
        run: |
          poetry install
      - name: Test
        working-directory: ./ossso_app
        run: |
          poetry run pytest

      - name: Build and publish to pypi
        if: github.event_name == 'release'
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
